name: PHPUnit

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  integration-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: [ '7.4', '8.1' ]
        composer-versions: [ '2.0', '2.3' ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:${{ matrix.composer-versions }}
          extensions: fileinfo

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run unit tests
        run: ./vendor/bin/phpunit --testsuite=Integration

