name: Code Static Analysis

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  phpmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpmd
        run: ./vendor/bin/phpmd ./src,./tests github ruleset.xml
